/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProjetoModeloCapacitacaoWebGradle;

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import io.github.bonigarcia.wdm.WebDriverManager;

import static org.junit.Assert.*;

public class LibraryTestt {
	
	@Test
	public void testProjetoModeloCapacitacaoWeb() throws InterruptedException {
	System.out.println("Test Gradleeeeeeeeeeee");  	
  
    WebDriverManager.chromedriver().setup();
    ChromeOptions options = new ChromeOptions();
    options.addArguments("--start-maximized");
    options.addArguments("--incognito");
    options.addArguments("--remote-allow-origins=*");
    WebDriver driver = new ChromeDriver(options);

    driver.get("https://seubarriga.wcaquino.me/");
    Thread.sleep(2000);
    
    WebElement getEmail = driver.findElement(By.id("email"));
    getEmail.click();
    getEmail.sendKeys("fgobby@gmail.com");
    
   
    WebElement getSenha = driver.findElement(By.id("senha"));
    getSenha.click();
    getSenha.sendKeys("123456");

    
    WebElement botaoRegistrar = driver.findElement(By.xpath("//*[@class='btn btn-primary']"));
    botaoRegistrar.click();
    
    String getMemsagemBemVindo = "Bem vindo, Francis !";          
    
    Thread.sleep(10000);

    if (driver != null) {
        driver.close();
    }
	}
}
